name: Build and Push Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: personal_token

    steps:
      - name: Checkout Source Code (Repo A)
        uses: actions/checkout@v3

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build Binaries
        run: |
           ./build.sh

      - name: Package Binaries
        run: |
            # 打印当前目录，确认文件结构
            ls ./  
            # 打印 bin 目录的内容，确保正确的文件存在
            ls ./bin/  
            # 使用 tar 压缩 ./bin 目录中的文件，并显示输出
            tar -czvf binaries.tar.gz -C ./bin .  # 使用 -C 选项进入 bin 目录
            # 打印压缩文件生成后，确认 binaries.tar.gz 的存在
            ls -lh binaries.tar.gz

      - name: Clone Repo B
        run: |
          cd ..
          # 克隆 Repo B 代码库
          git clone https://github.com/yliu098/repo_b.git
          cd repo_b

      - name: Checkout Repo B (with token)
        uses: actions/checkout@v3
        with:
          repository: yliu098/repo_b  # Repo B 的仓库名称
          token: ${{ secrets.test_token }}  # 使用存储在 Secrets 中的 token

      - name: Upload Binaries to Repo B
        run: |
          ls ./
          ls ../
          # 在 Repo B 中创建 'binaries' 目录并移动文件
          mkdir -p binaries
          mv ../repo_a/bin/binaries.tar.gz binaries/  # 将 Repo A 生成的二进制文件移动到 Repo B

          # 配置 Git 用户信息
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # 添加并提交变更
          git add binaries/
          git commit -m "Add new binaries from Repo A"
          git push
