name: Build and Push Binaries

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: personal_token

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up Build Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build Binaries
        run: |
           ./build.sh

      - name: Package Binaries
        run: |
          ls ./
          tar -czvf binaries.tar.gz ./bin

      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: yliu098/repo_b
          token: ${{ secrets.test_token }}

      - name: Upload Binaries to Repo B
        run: |
          # 确保 Repo B 中存在 binaries 目录
          mkdir -p binaries
          mv binaries.tar.gz binaries/

          # 配置 git 用户信息
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # 添加并提交更改
          git add binaries/
          git commit -m "Add new binaries from Repo A"
          git push
